name: Build and Release

on:
  push:
    tags:
      - 'v*'    #创建有v*的标签时运行

jobs:
  build:
    runs-on: windows-latest    #运行环境是Windows
    steps:
    - uses: actions/checkout@v2

    - name: 下载 Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 安装 MinGW64
      run: |
       @echo off
        set PATH=%PATH%;C:\MinGW64\bin
        if exist "%ProgramFiles%\Git\mingw64" (
          echo "Updating Git's MinGW64..."
          git config --global core.autocrlf input
        ) else (
          echo "Installing MinGW64..."
          powershell -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/WinRb/Win32-OpenSSH/master/OpenSSH-Win64.msi'))"
          echo "Installing MinGW64 via Chocolatey..."
          choco install mingw64 -y
        )
        echo "Installed MinGW64 successfully."

    - name: Test installation (optional)
      run: |
        @echo off
        echo "Testing installation..."
        g++ --version  # 使用g++ --version来检查MinGW64是否安装正确

    - name: 安装 Nuitka
      run: 
        pip install nuitka

    - name: 构建
      run: |
        nuitka --standalone --nofollow-imports --output-dir=dist --windows-disable-console --mingw64 --show-progress --file-version=0.0.1 --product-version=0.0.1 --icon=favicon.ico main.py

    - name: 重命名可执行文件
      run: |
        Rename-Item -Path "dist\main.exe" -NewName "OneKey.exe"

    - name: 创建发布
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: 上传发布
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/OneKey.exe
        asset_name: OneKey.exe
        asset_content_type: application/octet-stream
