# this workflow using github actions to build a binary exe file for windows users

name: Build

on:
  push:
    branches: ["main"]
  pull request:
    branches: ["main"]
  workflow dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      -uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1
          submodules: recursive

      -name: 安装Python 3.10
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"

      -name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      -name: 安装MinGW
        uses: egor-tensin/setup-mingw@v2.2.0
        with:
          platform: x64
          
      -name: 打包EXE
        run: |
          pip install nuitka
          nuitka --onefile --lto=no --report=report.xml --mingw64 --show-progress --show-memory --windows-icon-from-ico=favicon.ico main.py -n Onekey ${{ github.sha }}

      -name: 发布Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          body path: ./publish/changeLog.md
          prerlease: false
          draft: false
          tag name: 12.1
          files: |
            dist/OneKey ${{ github.sha }}.exe
          env:
            GITHUB TOKEN: ${{ secrets.GITHUB_TOKEN }}
